### ISSUE TITLE
rEGARDING THE STEEL BEEM FLORE

### ISSUE THREAD

**Issue by MathonIsonez** [dcontris/charlisetheron#4]
PLEASE DOUBLE CHECK QUANTITIES NEEDED IN TERMS OF CONTRUCTTORS ON THE PRODUCTION PLANNER AND THE QUANTIES BUILT ALSO ENSURE all the constructors are at max build capactisty flowage

**Comment by dcontris** [comment]
https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_SpaceElevatorPart_5_C%22%3A%225%22%7D

Just noting the planner link for my use

**Comment by dcontris** [comment]
lgtm (looks good to me)
